/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 *
 * (C) Copyright 2002-2003, Creativyst, Inc.
 *
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 *
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 328;

var quote = Array([lsz]);
var author = Array([lsz]);

quote[0] = "Nearly all men can stand adversity, but if you want to test a man\'s character, give him power.";
author[0] = "Abraham Lincoln";

quote[1] = "When I do good, I feel good; when I do bad, I feel bad, and that is my religion.";
author[1] = "Abraham Lincoln";

quote[2] = "To the man who only has a hammer, everything he encounters begins to look like a nail.";
author[2] = "Abraham Maslow";

quote[3] = "Time and space are modes by which we think and not conditions in which we live.";
author[3] = "Albert Einstein";

quote[4] = "When everyone is against you, it means that you are absolutely wrong-- or absolutely right.";
author[4] = "Albert Guinon";

quote[5] = "The art of progress is to preserve order amid change and to preserve change amid order.";
author[5] = "Alfred North Whitehead";

quote[6] = "The point of quotations is that one can use another\'s words to be insulting.";
author[6] = "Amanda Cross";

quote[7] = "Acquaintance, n.: A person whom we know well enough to borrow from, but not well enough to lend to.";
author[7] = "Ambrose Bierce";

quote[8] = "Courage is not the absence of fear, but rather the judgement that something else is more important than fear.";
author[8] = "Ambrose Redmoon";

quote[9] = "We don\'t see things as they are. We see things as we are.";
author[9] = "Anais Nin";

quote[10] = "The nice thing about standards is that there are so many of them to choose from.";
author[10] = "Andrew S. Tanenbaum";

quote[11] = "It is bad luck to be superstitious.";
author[11] = "Andrew W. Mathis";

quote[12] = "If the lessons of history teach us anything it is that nobody learns the lessons that history teaches us.";
author[12] = "Anon";

quote[13] = "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.";
author[13] = "Antoine de Saint-Exupéry";

quote[14] = "It is the mark of an educated mind to be able to entertain a thought without accepting it.";
author[14] = "Aristotle";

quote[15] = "Talent hits a target no one else can hit; Genius hits a target no one else can see.";
author[15] = "Arthur Schopenhauer";

quote[16] = "Every nation ridicules other nations, and all are right.";
author[16] = "Arthur Schopenhauer";

quote[17] = "I\'d rather live with a good question than a bad answer.";
author[17] = "Aryeh Frimer";

quote[18] = "The Argument from Intimidation is a confession of intellectual impotence.";
author[18] = "Ayn Rand";

quote[19] = "The real problem is not whether machines think but whether men do.";
author[19] = "B. F. Skinner";

quote[20] = "A wise man gets more use from his enemies than a fool from his friends.";
author[20] = "Baltasar Gracian";

quote[21] = "Good judgment comes from experience, and experience comes from bad judgment.";
author[21] = "Barry LePatner";

quote[22] = "Do not seek to follow in the footsteps of the men of old; seek what they sought.";
author[22] = "Basho";

quote[23] = "Who is wise? He who learns from all men.";
author[23] = "Ben Zoma";

quote[24] = "Never apologize for showing feeling. When you do so, you apologize for truth.";
author[24] = "Benjamin Disraeli";

quote[25] = "Either write something worth reading or do something worth writing.";
author[25] = "Benjamin Franklin";

quote[26] = "Time is the stuff life is made of.";
author[26] = "Benjamin Franklin";

quote[27] = "The tragedy of life doesn\'t lie in not reaching your goal. The tragedy lies in having no goals to reach.";
author[27] = "Benjamin Mays";

quote[28] = "What happens to the hole when the cheese is gone?";
author[28] = "Bertolt Brecht";

quote[29] = "The greatest challenge to any thinker is stating the problem in a way that will allow a solution.";
author[29] = "Bertrand Russell";

quote[30] = "No one gossips about other people\'s secret virtues.";
author[30] = "Bertrand Russell";

quote[31] = "I don\'t know the key to success, but the key to failure is trying to please everybody.";
author[31] = "Bill Cosby";

quote[32] = "If at first you don\'t succeed, find out if the loser gets anything.";
author[32] = "Bill Lyon";

quote[33] = "Thought is useful when it motivates for action, and a hindrance when it substitutes for action.";
author[33] = "Bill Raeder";

quote[34] = "We learn something every day, and lots of times it\'s that what we learned the day before was wrong.";
author[34] = "Bill Vaughan";

quote[35] = "An optimist stays up to see the New Year in. A pessimist waits to make sure the old one leaves.";
author[35] = "Bill Vaughan";

quote[36] = "Careful. We don\'t want to learn from this.";
author[36] = "Bill Watterson";

quote[37] = "I really wish I was less of a thinking man and more of a fool not afraid of rejection.";
author[37] = "Billy Joel";

quote[38] = "I have made this letter longer than usual because I lack the time to make it shorter.";
author[38] = "Blaise Pascal";

quote[39] = "A single question can be more influential than a thousand statements.";
author[39] = "Bo Bennett";

quote[40] = "A bank is a place that will lend you money if you can prove that you don\'t need it.";
author[40] = "Bob Hope";

quote[41] = "The less you know, the more you believe.";
author[41] = "Bono";

quote[42] = "You will not be punished for your anger, you will be punished by your anger.";
author[42] = "Buddha";

quote[43] = "When the student is ready the teacher will appear.";
author[43] = "Buddhist Proverb";

quote[44] = "Don\'t ever wrestle with a pig. You\'ll both get dirty, but the pig will enjoy it.";
author[44] = "Cale Yarborough";

quote[45] = "Everything that irritates us about others can lead us to an understanding of ourselves.";
author[45] = "Carl Jung";

quote[46] = "Who looks outside, dreams; who looks inside, awakes.";
author[46] = "Carl Jung";

quote[47] = "Some people make things happen, some people watch things happen, and some ask what happened.";
author[47] = "Casey Stengel";

quote[48] = "If you can\'t be a good example, then you\'ll just have to be a horrible warning.";
author[48] = "Catherine Aird";

quote[49] = "You don\'t get anything clean without getting something else dirty.";
author[49] = "Cecil Baxter";

quote[50] = "Happiness is the absence of striving for happiness.";
author[50] = "Chang-Tzu";

quote[51] = "Fight for your opinions, but do not believe that they contain the whole truth, or the only truth.";
author[51] = "Charles A. Dana";

quote[52] = "First we make our habits, then our habits make us.";
author[52] = "Charles C. Noble";

quote[53] = "An inventor is simply a fellow who doesn\'t take his education too seriously.";
author[53] = "Charles F. Kettering";

quote[54] = "Don\'t worry about the world coming to an end today. It\'s already tomorrow in Australia.";
author[54] = "Charles M. Schulz";

quote[55] = "By the time a man realizes that maybe his father was right, he usually has a son who thinks he\'s wrong.";
author[55] = "Charles Wadsworth";

quote[56] = "He who asks is a fool for five minutes, but he who does not ask remains a fool forever.";
author[56] = "Chinese Proverb";

quote[57] = "One dog barks at something. And a hundred dogs bark at the sound.";
author[57] = "Chinese Proverb";

quote[58] = "I hear: I forget / I see: I remember / I do: I understand";
author[58] = "Chinese Proverb";

quote[59] = "Asking a working writer what he thinks about critics is like asking a lamppost how it feels about dogs.";
author[59] = "Christopher Hampton";

quote[60] = "There is only one success - to be able to spend your life in your own way.";
author[60] = "Christopher Morley";

quote[61] = "Inspiration is for amateurs. I just get to work.";
author[61] = "Chuck Close";

quote[62] = "In theory, there is no difference between theory and practice; In practice, there is.";
author[62] = "Chuck Reid";

quote[63] = "When I was a boy I was told that anybody could become President. Now I\'m beginning to believe it.";
author[63] = "Clarence Darrow";

quote[64] = "Never believe anything until it has been officially denied.";
author[64] = "Claud Cockburn";

quote[65] = "Laughing at our mistakes can lengthen our own life. Laughing at someone else\'s can shorten it.";
author[65] = "Cullen Hightower";

quote[66] = "Better to write for yourself and have no public, than to write for the public and have no self.";
author[66] = "Cyril Connolly";

quote[67] = "There are many who dare not kill themselves for fear of what the neighbors will say.";
author[67] = "Cyril Connolly";

quote[68] = "Success is getting what you want. Happiness is wanting what you get.";
author[68] = "Dale Carnegie";

quote[69] = "Never be afraid to laugh at yourself, after all, you could be missing out on the joke of the century.";
author[69] = "Dame Edna Everage";

quote[70] = "Do not condemn the judgement of another because it differs from your own. You may both be wrong.";
author[70] = "Dandemis";

quote[71] = "The greatest obstacle to discovery is not ignorance - it is the illusion of knowledge.";
author[71] = "Daniel J. Boorstin";

quote[72] = "Procastination is not about not doing is about not doing and feeling crappy.";
author[72] = "David Allen";

quote[73] = "You can do anything, but not everything.";
author[73] = "David Allen";

quote[74] = "A committee can make a decision that is dumber than any of its members.";
author[74] = "David Cobitz";

quote[75] = "Television enables you to be entertained in your home by people you wouldn\'t have in your home.";
author[75] = "David Frost";

quote[76] = "Don\'t be afraid to take a big step if one is indicated. You can\'t cross a chasm in two small jumps.";
author[76] = "David Lloyd George";

quote[77] = "The tooth fairy teaches children that they can sell body parts for money.";
author[77] = "David Richerby";

quote[78] = "The more you know, the more you realise how much you don\'t know -- the less you know, the more you think you know.";
author[78] = "David T. Freeman";

quote[79] = "The first step toward success will be the biggest one.";
author[79] = "Dennis Waitley";

quote[80] = "There\'s so much comedy on television. Does that cause comedy in the streets?";
author[80] = "Dick Cavett";

quote[81] = "It\'s a rare person who wants to hear what he doesn\'t want to hear.";
author[81] = "Dick Cavett";

quote[82] = "If your parents never had children, chances are you won\'t, either.";
author[82] = "Dick Cavett";

quote[83] = "There is nobody so irritating as somebody with less intelligence and more sense than we have.";
author[83] = "Don Herold";

quote[84] = "Procrastination is the art of keeping up with yesterday.";
author[84] = "Don Marquis";

quote[85] = "If you are not criticized, you may not be doing much.";
author[85] = "Donald H. Rumsfeld";

quote[86] = "I don\'t care what is written about me so long as it isn\'t true.";
author[86] = "Dorothy Parker";

quote[87] = "The art of simplicity is a puzzle of complexity.";
author[87] = "Doug Horton";

quote[88] = "Instead of giving a politician the keys to the city, it might be better to change the locks.";
author[88] = "Doug Larson";

quote[89] = "I love deadlines. I like the whooshing sound they make as they fly by.";
author[89] = "Douglas Adams";

quote[90] = "Hofstadter\'s Law: It always takes longer than you expect, even when you take into account Hofstadter\'s Law.";
author[90] = "Douglas Hofstadter";

quote[91] = "In God we trust; all others bring data.";
author[91] = "Dr. Edwards Deming";

quote[92] = "Be who you are and say what you feel, because those who mind don\'t matter and those who matter don\'t mind.";
author[92] = "Dr. Seuss";

quote[93] = "The best car safety device is a rear-view mirror with a cop in it.";
author[93] = "Dudley Moore";

quote[94] = "In preparing for battle I have always found that plans are useless, but planning is indispensable.";
author[94] = "Dwight D. Eisenhower";

quote[95] = "Computer Science is no more about computers than astronomy is about telescopes.";
author[95] = "E. W. Dijkstra";

quote[96] = "I am patient with stupidity but not with those who are proud of it.";
author[96] = "Edith Sitwell";

quote[97] = "If only we\'d stop trying to be happy we could have a pretty good time.";
author[97] = "Edith Wharton";

quote[98] = "Talent does what it can; genius does what it must.";
author[98] = "Edward Bulwer-Lytton";

quote[99] = "The skill of writing is to create a context in which other people can think.";
author[99] = "Edwin Schlossberg";

quote[100] = "No one can make you feel inferior without your consent.";
author[100] = "Eleanor Roosevelt";

quote[101] = "The cure for boredom is curiosity. There is no cure for curiosity.";
author[101] = "Ellen Parr";

quote[102] = "I don\'t know anything about music. In my line you don\'t have to.";
author[102] = "Elvis Presley";

quote[103] = "If the human mind was simple enough to understand, we\'d be too simple to understand it.";
author[103] = "Emerson Pugh";

quote[104] = "If voting changed anything, they\'d make it illegal.";
author[104] = "Emma Goldman";

quote[105] = "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.";
author[105] = "Epitectus";

quote[106] = "You can discover what your enemy fears most by observing the means he uses to frighten you.";
author[106] = "Eric Hoffer";

quote[107] = "When people are free to do as they please, they usually imitate each other.";
author[107] = "Eric Hoffer";

quote[108] = "You can never get enough of what you don\'t really need.";
author[108] = "Eric Hoffer";

quote[109] = "Advice is what we ask for when we already know the answer but wish we didn\'t.";
author[109] = "Erica Jong";

quote[110] = "You can\'t get away from yourself by moving from one place to another. There\'s nothing to that.";
author[110] = "Ernest Hemingway";

quote[111] = "Courage is grace under pressure.";
author[111] = "Ernest Hemingway";

quote[112] = "Character is what you have left when you\'ve lost everything you can lose.";
author[112] = "Evan Esar";

quote[113] = "An incompetent attorney can delay a trial for months or years. A competent attorney can delay one even longer.";
author[113] = "Evelle J. Younger";

quote[114] = "I\'ve done the calculation and your chances of winning the lottery are identical whether you play or not.";
author[114] = "Fran Lebowitz";

quote[115] = "We confess our little faults to persuade people that we have no large ones.";
author[115] = "Francois de La Rochefoucauld";

quote[116] = "If you don\'t make mistakes, you\'re not working on hard enough problems. And that\'s a big mistake.";
author[116] = "Frank Wilczek";

quote[117] = "Writing about music is like dancing about architecture.";
author[117] = "Frank Zappa";

quote[118] = "Honest criticism is hard to take, particularly from a relative, a friend, an acquaintance, or a stranger.";
author[118] = "Franklin P. Jones";

quote[119] = "Experience is that marvelous thing that enables you to recognize a mistake when you make it again.";
author[119] = "Franklin P. Jones";

quote[120] = "The trouble with being punctual is that nobody\'s there to appreciate it.";
author[120] = "Franklin P. Jones";

quote[121] = "A celebrity is a person who works hard all his life to become well known, then wears dark glasses to avoid being recognized.";
author[121] = "Fred Allen";

quote[122] = "I can\'t understand why a person will take a year to write a novel when he can easily buy one for a few dollars.";
author[122] = "Fred Allen";

quote[123] = "Insanity in individuals is something rare - but in groups, parties, nations and epochs, it is the rule.";
author[123] = "Friedrich Nietzsche";

quote[124] = "The man of knowledge must be able not only to love his enemies but also to hate his friends.";
author[124] = "Friedrich Nietzsche";

quote[125] = "Education... has produced a vast population able to read but unable to distinguish what is worth reading.";
author[125] = "G. M. Trevelyan";

quote[126] = "I have never met a man so ignorant that I couldn\'t learn something from him.";
author[126] = "Galileo Galilei";

quote[127] = "The difference between what we do and what we are capable of doing would solve most the worlds problems.";
author[127] = "Gandhi";

quote[128] = "A man is but the product of his thoughts; what he thinks, he becomes.";
author[128] = "Gandhi";

quote[129] = "An eye for eye only ends up making the whole world blind.";
author[129] = "Gandhi";

quote[130] = "You must be the change you wish to see in the world.";
author[130] = "Gandhi";

quote[131] = "God has no religion.";
author[131] = "Gandhi";

quote[132] = "My friends tell me I have an intimacy problem. But they don\'t really know me.";
author[132] = "Garry Shandling";

quote[133] = "I\'ve been trying for some time to develop a lifestyle that doesn\'t require my presence.";
author[133] = "Gary Trudeau";

quote[134] = "Everyone is a genius at least once a year. The real geniuses simply have their bright ideas closer together.";
author[134] = "Georg Christoph Lichtenberg";

quote[135] = "The nice part about being a pessimist is that you are constantly being either proven right or pleasantly surprised.";
author[135] = "George F. Will";

quote[136] = "All animals are equal but some animals are more equal than others.";
author[136] = "George Orwell";

quote[137] = "Those who cannot remember the past are condemned to repeat it.";
author[137] = "George Santayana";

quote[138] = "A physicist is an atom\'s way of knowing about atoms.";
author[138] = "George Wald";

quote[139] = "Why does the Air Force need expensive new bombers? Have the people we\'ve been bombing over the years been complaining?";
author[139] = "George Wallace";

quote[140] = "I have too much respect for the idea of God to make it responsible for such an absurd world.";
author[140] = "Georges Duhamel";

quote[141] = "Some people like my advice so much that they frame it upon the wall instead of using it.";
author[141] = "Gordon R. Dickson";

quote[142] = "2 is not equal to 3, not even for large values of 2.";
author[142] = "Grabel\'s Law";

quote[143] = "A man is rich in proportion to the number of things he can afford to let alone.";
author[143] = "Henry David Thoreau";

quote[144] = "Every generation laughs at the old fashions, but follows religiously the new.";
author[144] = "Henry David Thoreau";

quote[145] = "Whether you think you can or think you can\'t -- you are right.";
author[145] = "Henry Ford";

quote[146] = "I hope that while so many people are out smelling the flowers, someone is taking the time to plant some.";
author[146] = "Herbert Rappaport";

quote[147] = "If you hate a person, you hate something in him that is part of yourself. What isn\'t part of ourselves doesn\'t disturb us.";
author[147] = "Hermann Hesse";

quote[148] = "Writing is good, thinking is better. Cleverness is good, patience is better";
author[148] = "Hermann Hesse";

quote[149] = "I never apologize. I\'m sorry, but that\'s just the way I am.";
author[149] = "Homer Simpson";

quote[150] = "The whole secret of life is to be interested in one thing profoundly and in a thousand things well.";
author[150] = "Horace Walpole";

quote[151] = "Science is organized knowledge. Wisdom is organized life.";
author[151] = "Immanuel Kant";

quote[152] = "If the doctor told me I had six minutes to live, I\'d type a little faster.";
author[152] = "Isaac Asimov";

quote[153] = "If I have seen further it is by standing on the shoulders of giants.";
author[153] = "Isaac Newton";

quote[154] = "Once the game is over, the King and the pawn go back in the same box.";
author[154] = "Italian Proverb";

quote[155] = "Never judge a book by its movie.";
author[155] = "J. W. Eagan";

quote[156] = "I don\'t deserve this award, but I have arthritis and I don\'t deserve that either.";
author[156] = "Jack Benny";

quote[157] = "It\'s no longer a question of staying healthy. It\'s a question of finding a sickness you like.";
author[157] = "Jackie Mason";

quote[158] = "I have enough money to last me the rest of my life, unless I buy something.";
author[158] = "Jackie Mason";

quote[159] = "The world can only be grasped by action, not by contemplation.";
author[159] = "Jacob Bronowski";

quote[160] = "Dream as if you\'ll live forever. Live as if you\'ll die today.";
author[160] = "James Dean";

quote[161] = "Too many people are thinking of security instead of opportunity. They seem more afraid of life than death.";
author[161] = "James F. Byrnes";

quote[162] = "A myth is a religion in which no one any longer believes.";
author[162] = "James Feibleman";

quote[163] = "It is better to know some of the questions than all of the answers.";
author[163] = "James Thurber";

quote[164] = "He knows all about art, but he doesn\'t know what he likes.";
author[164] = "James Thurber";

quote[165] = "No matter what side of the argument you are on, you always find people on your side that you wish were on the other.";
author[165] = "Jascha Heifetz";

quote[166] = "Life is like a game of cards. The hand that is dealt you is determinism; the way you play it is free will.";
author[166] = "Jawaharlal Nehru";

quote[167] = "Only the mediocre are always at their best.";
author[167] = "Jean Giraudoux";

quote[168] = "A timid person is frightened before a danger, a coward during the time, and a courageous person afterward.";
author[168] = "Jean Paul Richter";

quote[169] = "My pessimism extends to the point of even suspecting the sincerity of the pessimists.";
author[169] = "Jean Rostand";

quote[170] = "A good tool improves the way you work.  A great tool improves the way you think.";
author[170] = "Jeff Duntemann";

quote[171] = "A person who trusts no one can\'t be trusted.";
author[171] = "Jerome Blattner";

quote[172] = "I like work: it fascinates me. I can sit and look at it for hours.";
author[172] = "Jerome K. Jerome";

quote[173] = "Sometimes the road less traveled is less traveled for a reason.";
author[173] = "Jerry Seinfeld";

quote[174] = "If God lived on earth, people would break his windows.";
author[174] = "Jewish Proverb";

quote[175] = "If the phone doesn\'t ring, it\'s me.";
author[175] = "Jimmy Buffet";

quote[176] = "We are the people our parents warned us about.";
author[176] = "Jimmy Buffett";

quote[177] = "The only normal people are the ones you don\'t know very well.";
author[177] = "Joe Ancis";

quote[178] = "If it weren\'t for my lawyer, I\'d still be in prison. It went a lot faster with two people digging.";
author[178] = "Joe Martin";

quote[179] = "It is in self-limitation that a master first shows himself.";
author[179] = "Johann Goethe";

quote[180] = "In mathematics you don\'t understand things. You just get used to them.";
author[180] = "Johann von Neumann";

quote[181] = "The intelligent man finds almost everything ridiculous, the sensible man hardly anything.";
author[181] = "Johann Wolfgang von Goethe";

quote[182] = "The only function of economic forecasting is to make astrology look respectable.";
author[182] = "John Kenneth Galbraith";

quote[183] = "Time you enjoy wasting is not wasted.";
author[183] = "John Lennon";

quote[184] = "A man always has two reasons for what he does-a good one, and the real one.";
author[184] = "John Pierpont Morgan";

quote[185] = "We are continually faced with a series of great opportunities brilliantly disguised as insoluble problems.";
author[185] = "John W. Gardner";

quote[186] = "Half the money I spend on advertising is wasted; the trouble is I don\'t know which half.";
author[186] = "John Wanamaker";

quote[187] = "Before I got married I had six theories about bringing up children; now I have six children and no theories.";
author[187] = "John Wilmot";

quote[188] = "No wise man ever wished to be younger.";
author[188] = "Jonathan Swift";

quote[189] = "Man has to suffer. When he has no real afflictions, he invents some.";
author[189] = "Jose Marti";

quote[190] = "I hate mankind, for I think myself one of the best of them, and I know how bad I am.";
author[190] = "Joseph Baretti";

quote[191] = "A fine quotation is a diamond on the finger of a man of wit, and a pebble in the hand of a fool.";
author[191] = "Joseph Roux";

quote[192] = "A single death is a tragedy; a million deaths is a statistic.";
author[192] = "Joseph Stalin";

quote[193] = "Always be a first-rate version of yourself, instead of a second-rate version of someone else.";
author[193] = "Judy Garland";

quote[194] = "Imagination is the one weapon in the war against reality.";
author[194] = "Jules de Gaultier";

quote[195] = "I don\'t know if God exists, but it would be better for His reputation if He didn\'t.";
author[195] = "Jules Renard";

quote[196] = "Laziness is nothing more than the habit of resting before you get tired.";
author[196] = "Jules Renard";

quote[197] = "It is no measure of health to be well adjusted to a profoundly sick society.";
author[197] = "Krishnamurti";

quote[198] = "I\'d rather be hated for who I am, than loved for who I am not.";
author[198] = "Kurt Cobain";

quote[199] = "If you want truly to understand something, try to change it.";
author[199] = "Kurt Lewin";

quote[200] = "Another flaw in the human character is that everybody wants to build and nobody wants to do maintenance.";
author[200] = "Kurt Vonnegut";

quote[201] = "Those who believe in telekinetics, raise my hand.";
author[201] = "Kurt Vonnegut";

quote[202] = "A journey of a thousand miles begins with a single step.";
author[202] = "Lao Tzu";

quote[203] = "Truth over Harmony.";
author[203] = "Larry Bossidy";

quote[204] = "Originality is the fine art of remembering what you hear but forgetting where you heard it.";
author[204] = "Laurence J. Peter";

quote[205] = "Any event, once it has occurred, can be made to appear inevitable by a competent historian.";
author[205] = "Lee Simonson";

quote[206] = "Everyone thinks of changing the world, but no one thinks of changing himself.";
author[206] = "Leo Tolstoy";

quote[207] = "Simplicity is the ultimate sophistication.";
author[207] = "Leonardo da Vinci";

quote[208] = "When hungry, eat your rice; when tired, close your eyes. Fools may laugh at me, but wise men will know what I mean.";
author[208] = "Lin-Chi";

quote[209] = "The best way to have a good idea is to have lots of ideas.";
author[209] = "Linus Pauling";

quote[210] = "The highest proof of virtue is to possess boundless power without abusing it.";
author[210] = "Lord Macaulay";

quote[211] = "Life is ten percent what happens to you and ninety percent how you respond to it.";
author[211] = "Lou Holtz";

quote[212] = "Love thy neighbour as yourself, but choose your neighbourhood.";
author[212] = "Louise Beal";

quote[213] = "Wisdom is knowing the right path to take… Integrity is taking it.";
author[213] = "M. H. McKee";

quote[214] = "It is more important to know where you are going than to get there quickly.";
author[214] = "Mabel Newcomber";

quote[215] = "Education\'s purpose is to replace an empty mind with an open one.";
author[215] = "Malcolm Forbes";

quote[216] = "The real voyage of discovery consists not in seeking new lands but seeing with new eyes.";
author[216] = "Marcel Proust";

quote[217] = "Most conversations are simply monologues delivered in the presence of witnesses.";
author[217] = "Margaret Millar";

quote[218] = "Until you\'ve lost your reputation, you never realize what a burden it was.";
author[218] = "Margaret Mitchell";

quote[219] = "Even a stopped clock is right twice a day.";
author[219] = "Marie von Ebner-Eschenbach";

quote[220] = "Times have not become more violent. They have just become more televised.";
author[220] = "Marilyn Manson";

quote[221] = "To acquire knowledge, one must study; but to acquire wisdom, one must observe.";
author[221] = "Marilyn vos Savant";

quote[222] = "If everything\'s under control, you\'re going too slow.";
author[222] = "Mario Andretti";

quote[223] = "It is surprinsingly how easy it is to forget that the way to get things done is to do them.";
author[223] = "Mark Forster";

quote[224] = "Silence is so accurate.";
author[224] = "Mark Rothko";

quote[225] = "The difference between the right word and the almost right word is the difference between lightning and a lightning bug.";
author[225] = "Mark Twain";

quote[226] = "To cease smoking is the easiest thing I ever did; I ought to know because I\'ve done it a thousand times.";
author[226] = "Mark Twain";

quote[227] = "When a thought is too weak to be expressed simply, simply drop it.";
author[227] = "Marquis de Vauvenargues";

quote[228] = "A man who fears suffering is already suffering from what he fears.";
author[228] = "Montaigne";

quote[229] = "We can do no great things, only small things with great love.";
author[229] = "Mother Teresa";

quote[230] = "You can tell whether a man is clever by his answers. You can tell whether a man is wise by his questions.";
author[230] = "Naguib Mahfouz";

quote[231] = " Never ascribe to malice, that which can be explained by incompetence.";
author[231] = "Napoleon (Hanlon\'s Razor)";

quote[232] = "History is the version of past events that people have decided to agree upon.";
author[232] = "Napoleon Bonaparte";

quote[233] = "Never interrupt your enemy when he is making a mistake.";
author[233] = "Napoleon Bonaparte";

quote[234] = "I like long walks, especially when they are taken by people who annoy me.";
author[234] = "Noel Coward";

quote[235] = "Insane people are always sure that they are fine. It is only the sane people who are willing to admit that they are crazy.";
author[235] = "Nora Ephron";

quote[236] = "Heroism consists of hanging on one minute longer.";
author[236] = "Norwegian saying";

quote[237] = "You probably wouldn\'t worry about what people think of you if you could know how seldom they do.";
author[237] = "Olin Miller";

quote[238] = "The little I know I owe to my ignorance.";
author[238] = "Orville Mars";

quote[239] = "What the world needs is more geniuses with humility, there are so few of us left. ";
author[239] = "Oscar Levant";

quote[240] = "There is no such thing as a moral or an immoral book. Books are well written or badly written.";
author[240] = "Oscar Wilde";

quote[241] = "Truth, in matters of religion, is simply the opinion that has survived.";
author[241] = "Oscar Wilde";

quote[242] = "Always forgive your enemies; nothing annoys them so much.";
author[242] = "Oscar Wilde";

quote[243] = "Computers are useless. They can only give you answers.";
author[243] = "Pablo Picasso";

quote[244] = "Action is the foundational key to all success.";
author[244] = "Pablo Picasso";

quote[245] = "A genius! For 37 years I\'ve practised fourteen hours a day, and now they call me a genius!";
author[245] = "Pablo Sarasate (Spanish Violinist)";

quote[246] = "The best way to make your dreams come true is to wake up.";
author[246] = "Paul Valery";

quote[247] = "There is nothing so useless as doing efficiently that which should not be done at all.";
author[247] = "Peter F. Drucker";

quote[248] = "Some people have so much respect for their superiors they have none left for themselves.";
author[248] = "Peter McArthur";

quote[249] = "Wise men talk because they have something to say; fools, because they have to say something.";
author[249] = "Plato";

quote[250] = "Write drunk, revise sober.";
author[250] = "Poet\'s Motto";

quote[251] = "Some things have to be believed to be seen.";
author[251] = "Ralph Hodgson";

quote[252] = "The test of courage comes when we are in the minority. The test of tolerance comes when we are in the majority.";
author[252] = "Ralph W. Sockman";

quote[253] = "I hate quotations. Tell me what you know.";
author[253] = "Ralph Waldo Emerson";

quote[254] = "You have to know how to accept rejection and reject acceptance.";
author[254] = "Ray Bradbury";

quote[255] = "Each problem that I solved became a rule which served afterwards to solve other problems.";
author[255] = "Rene Descartes";

quote[256] = "I quit therapy because my analyst was trying to help me behind my back.";
author[256] = "Richard Lewis";

quote[257] = "One of the keys to happiness is a bad memory.";
author[257] = "Rita Mae Brown";

quote[258] = "An undefined problem has an infinite number of solutions.";
author[258] = "Robert A. Humphrey";

quote[259] = "Quiet is the absence of sound. Silence is the presence of silence.";
author[259] = "Robert Fripp";

quote[260] = "Understanding is simple. Knowing is complicated.";
author[260] = "Robert Fripp";

quote[261] = "Two roads diverged in a wood, and I--/ I took the one less traveled by, / And that has made all the difference.";
author[261] = "Robert Frost";

quote[262] = "The true measure of a man is how he treats someone who can do him absolutely no good.";
author[262] = "Samuel Johnson";

quote[263] = "What is written without effort is in general read without pleasure.";
author[263] = "Samuel Johnson";

quote[264] = "If you can eliminate all the other choices, the remaining choice, no matter how improbable, is the answer.";
author[264] = "Sherlock Holmes";

quote[265] = "In the beginner\'s mind there are many possibilities, but in the expert\'s there are few.";
author[265] = "Shunryu Suzuki";

quote[266] = "An honest politician is one who, when he is bought, will stay bought.";
author[266] = "Simon Cameron";

quote[267] = "An honest politician is one who, when he is bought, will stay bought.";
author[267] = "Simon Cameron";

quote[268] = "Not only is the universe stranger than we imagine, it is stranger than we can imagine.";
author[268] = "Sir Arthur Eddington";

quote[269] = "I don\'t mind what language an opera is sung in so long as it is a language I don\'t understand.";
author[269] = "Sir Edward Appleton";

quote[270] = "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.";
author[270] = "Socrates";

quote[271] = "The only true wisdom is in knowing you know nothing.";
author[271] = "Socrates";

quote[272] = "The unexamined life is not worth living.";
author[272] = "Socrates";

quote[273] = "Tomorrow is often the busiest day of the week.";
author[273] = "Spanish Proverb";

quote[274] = "To a brave man, good and bad luck are like his left and right hand. He uses both.";
author[274] = "St Catherine of Siena";

quote[275] = "\'Someday\' is the day after you die.";
author[275] = "Steve Pavlina";

quote[276] = "Failure to plan ahead on your part does not create an emergency on my part.";
author[276] = "Steven Dutch";

quote[277] = "Millions long for immortality who do not know what to do with themselves on a rainy Sunday afternoon.";
author[277] = "Susan Erz";

quote[278] = "Fortune does not change men, it unmasks them.";
author[278] = "Suzanne Necker";

quote[279] = "When I hear somebody sigh, \'Life is hard,\' I am always tempted to ask, \'Compared to what?\'";
author[279] = "Sydney J. Harris";

quote[280] = "If I had to live my life again, I\'d make the same mistakes, only sooner.";
author[280] = "Tallulah Bankhead";

quote[281] = "We don\'t see the things the way they are. We see things the way WE are.";
author[281] = "Talmund";

quote[282] = "If I only had a little humility, I\'d be perfect.";
author[282] = "Ted Turner";

quote[283] = "There is nothing so easy but that it becomes difficult when you do it reluctantly.";
author[283] = "Terence";

quote[284] = "Every great advance in natural knowledge has involved the absolute rejection of authority.";
author[284] = "Thomas H. Huxley";

quote[285] = "Try to learn something about everything and everything about something.";
author[285] = "Thomas H. Huxley";

quote[286] = "The way to succeed is to double your error rate.";
author[286] = "Thomas J. Watson";

quote[287] = "A government that is big enough to give you all you want is big enough to take it all away.";
author[287] = "Thomas Jefferson";

quote[288] = "A writer is someone for whom writing is more difficult than it is  for other people.";
author[288] = "Thomas Manne";

quote[289] = "In archaeology you uncover the unknown. In diplomacy you cover the known.";
author[289] = "Thomas Pickering";

quote[290] = "There are only two ways of telling the complete truth--anonymously and posthumously.";
author[290] = "Thomas Sowell";

quote[291] = "When a person can no longer laugh at himself, it is time for others to laugh at him.";
author[291] = "Thomas Szasz";

quote[292] = "Invention is the mother of necessity.";
author[292] = "Thorstein Veblen";

quote[293] = "I have such a high regard for the truth that I use it sparingly.";
author[293] = "Timothy Connor";

quote[294] = "Women who seek to be equal with men lack ambition.";
author[294] = "Timothy Leary";

quote[295] = "A cult is a religion with no political power.";
author[295] = "Tom Wolfe";

quote[296] = "The best way to get a better answer is to start asking a better question.";
author[296] = "Tony Robbins";

quote[297] = "The things you own end up owning you.";
author[297] = "Tyler Durden, in Fight Club";

quote[298] = "The real hero is always a hero by mistake; he dreams of being an honest coward like everybody else.";
author[298] = "Umberto Eco";

quote[299] = "Experience is a hard teacher because she gives the test first, the lesson afterwards.";
author[299] = "Vernon Sanders Law";

quote[300] = "Laughter is the shortest distance between two people.";
author[300] = "Victor Borge";

quote[301] = "I don\'t mind what Congress does, as long as they don\'t do it in the streets and frighten the horses.";
author[301] = "Victor Hugo";

quote[302] = "Practice doesn\'t make perfect. Perfect practice makes perfect.";
author[302] = "Vince Lombardi";

quote[303] = "The very best thing you can do for the whole world is to make the most of yourself.";
author[303] = "Wallace Wattles";

quote[304] = "You\'ve achieved success in your field when you don\'t know whether what you\'re doing is work or play.";
author[304] = "Warren Beatty";

quote[305] = "It makes more sense to buy a wonderful business at a fair price than it does to buy a fair business at a wonderful price.";
author[305] = "Warren Buffet";

quote[306] = "You miss 100 percent of the shots you never take.";
author[306] = "Wayne Gretzky";

quote[307] = "Always and never are two words you should always remember never to use.";
author[307] = "Wendell Johnson";

quote[308] = "Research is what I\'m doing when I don\'t know what I\'m doing.";
author[308] = "Wernher von Braun";

quote[309] = "The difference between death and taxes is death doesn\'t get worse every time Congress meets.";
author[309] = "Will Rogers";

quote[310] = "Even if you\'re on the right track, you\'ll get run over if you just sit there.";
author[310] = "Will Rogers";

quote[311] = "The trouble with being poor is that it takes up all of your time.";
author[311] = "Willem de Kooning";

quote[312] = "The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails.";
author[312] = "William Arthur Ward";

quote[313] = "It is easier to forgive an enemy than to forgive a friend.";
author[313] = "William Blake";

quote[314] = "It is impossible to defeat an ignorant man in argument.";
author[314] = "William G. McAdoo";

quote[315] = "The future is here. It\'s just not widely distributed yet.";
author[315] = "William Gibson";

quote[316] = "I feel like a fugitive from the law of averages.";
author[316] = "William H. Mauldin";

quote[317] = "After one look at this planet any visitor from outer space would say I want to see the manager.";
author[317] = "William S. Burroughs";

quote[318] = "When two men in business always agree, one of them is unnecessary.";
author[318] = "William Wrigley Jr.";

quote[319] = "I respect faith, but doubt is what gets you an education.";
author[319] = "Wilson Mizner";

quote[320] = "Success consists of going from failure to failure without loss of enthusiasm.";
author[320] = "Winston Churchill";

quote[321] = "A fanatic is one who can\'t change his mind and won\'t change the subject.";
author[321] = "Winston Churchill";

quote[322] = "If you\'re not failing every now and again, it\'s a sign you\'re not doing anything very innovative.";
author[322] = "Woody Allen";

quote[323] = "I took a speed reading course and read \'War and Peace\' in twenty minutes. It involves Russia.";
author[323] = "Woody Allen";

quote[324] = "Eighty percent of success is showing up.";
author[324] = "Woody Allen";

quote[325] = "No one goes there nowadays, it\'s too crowded.";
author[325] = "Yogi Berra";

quote[326] = "Before enlightnment, chop wood, carry water. After enlightnment, chop wood, carry water.";
author[326] = "Zen proverb";

quote[327] = "People often say that motivation doesn\'t last. Well, neither does bathing - that\'s why we recommend it daily.";
author[327] = "Zig Ziglar";
